<a href="https://colab.research.google.com/github/koidula/POSII/blob/main/%D0%9B%D0%B0%D0%BD%D0%B4%D1%8B%D0%B7%D0%B8%D0%BD_%D0%9F%D0%9E%D0%A1%D0%98%D0%98_%D0%9F%D0%A01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Часть 1 **NumPy**
\
Во всех заданиях данного раздела запрещено использовать циклы и list
comprehensions. Под вектором и матрицей в данных заданиях понимается
одномерный и двумерный numpy.array соответственно.



In [ ]:
import numpy as np

#1 
Реализуйте функцию, возвращающую максимальный элемент в векторе x
среди элементов, перед которыми стоит нулевой. Для x = np.array([6, 2, 0, 3, 0,
0, 5, 7, 0]) ответом является 5 Если нулевых элементов нет, функция должна
возвращать None.

In [ ]:
def max_after0(arr):
    x = arr == 0 # x - массив содержащий True для каждого нулевого элемента массива arr
    #создаётся новый массив after_zero, который содержит все элементы arr, следующие за нулями. Для этого мы сначала берём 
    #подмассив arr[1:], содержащий все элементы arr, кроме первого, 
    #затем используем маску x[:-1], чтобы выбрать только те элементы arr[1:], которые следуют за нулевыми элементами arr.
    after_zero = arr[1:][x[:-1]]
    if after_zero.size > 0:
        return after_zero.max()
    else:
        return None

In [ ]:
a = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) #5
print(max_after0(a),"\n")
b = np.random.randint(10, size=10)
print(max_after0(b))

5 

7


#2 
Реализуйте функцию, принимающую на вход матрицу и некоторое число и
возвращающую ближайший к числу элемент матрицы. Например: для X =
np.arange(0,10).reshape((2, 5)) и v = 3.6 ответом будет 4


In [ ]:
def nearest_value(matrix, v):
    flattened_matrix = matrix.flatten()  # Превращаем матрицу в одномерный массив
    idx = np.abs(flattened_matrix - v).argmin()  # Индекс ближайшего элемента
    return flattened_matrix[idx]  # Возвращаем ближайший элемент

In [ ]:
X = np.arange(0,10).reshape((2, 5)) 
v = 3.6
nearest_value(X, v)

4

In [ ]:
A = np.arange(6).reshape(2,3) + 10
v = 13.51
nearest_value(A, v)

14

#3
Реализуйте функцию scale(X), которая принимает на вход матрицу и
масштабирует каждый ее столбец (вычитает выборочное среднее и делит на
стандартное отклонение). Убедитесь, что в функции не будет происходить
деления на ноль. Протестируйте на случайной матрице (для её генерации
можно использовать, например, функцию numpy.random.randint).


In [ ]:
def scale(X):
    # Вычисляем среднее и стандартное отклонение по каждому столбцу
    col_mean = np.mean(X, axis=0)
    col_std = np.std(X, axis=0)
    
    # Заменяем нулевые стандартные отклонения на единицу, чтобы избежать деления на ноль
    col_std[col_std == 0] = 1
    
    # Масштабируем каждый столбец
    scaled_X = (X - col_mean) / col_std
    
    return scaled_X

In [ ]:
# Генерируем случайную матрицу
X = np.random.randint(low=0, high=10, size=(5, 5))
print("Matrix")
print(X)

# Масштабируем каждый столбец матрицы
scaled_X = scale(X)
print("Scaled matrix")
print(scaled_X)

Matrix
[[8 3 0 4 7]
 [3 4 5 9 6]
 [6 1 4 2 1]
 [9 9 7 9 6]
 [5 0 5 5 8]]
Scaled matrix
[[ 0.84292723 -0.12751534 -1.81412369 -0.64616234  0.57932412]
 [-1.4985373   0.19127301  0.34554737  1.14873305  0.16552118]
 [-0.09365858 -0.76509206 -0.08638684 -1.3641205  -1.90349354]
 [ 1.31122014  1.7852148   1.2094158   1.14873305  0.16552118]
 [-0.56195149 -1.08388041  0.34554737 -0.28718326  0.99312707]]


#4 
Реализуйте функцию, которая для заданной матрицы находит:

*   определитель
*   след
*   наименьший и наибольший элементы
*   норму Фробениуса
*   собственные числа
*   обратную матрицу

Для тестирования сгенерируйте матрицу с элементами из нормального распределения N(10,1)

In [ ]:
def matrix_stats(X):
    # Находим определитель
    det_X = np.linalg.det(X)
    
    # Находим след
    trace_X = np.trace(X)
    
    # Находим наименьший и наибольший элементы
    min_X = np.min(X)
    max_X = np.max(X)
    
    # Находим норму Фробениуса
    frob_norm_X = np.linalg.norm(X, ord='fro')
    
    # Находим собственные числа
    eigenvals_X = np.linalg.eigvals(X)
    
    # Находим обратную матрицу
    inv_X = np.linalg.inv(X)
    
    # Возвращаем результаты
    return det_X, trace_X, min_X, max_X, frob_norm_X, eigenvals_X, inv_X

In [ ]:
# Генерируем матрицу размера 3x3 со значениями из нормального распределения N(10,1)
X = np.random.normal(loc=10, scale=1, size=(3, 3))
print("Исходная матрица:")
print(X)

# Вычисляем статистики матрицы
det_X, trace_X, min_X, max_X, frob_norm_X, eigenvals_X, inv_X = matrix_stats(X)

# Выводим результаты на экран
print("Определитель матрицы:", det_X)
print("След матрицы:", trace_X)
print("Наименьший элемент матрицы:", min_X)
print("Наибольший элемент матрицы:", max_X)
print("Норма Фробениуса матрицы:", frob_norm_X)
print("Собственные числа матрицы:", eigenvals_X)
print("Обратная матрица:")
print(inv_X)

Исходная матрица:
[[10.51965592  9.12325022  9.12449412]
 [ 8.39286801 11.63950272  9.80385971]
 [ 9.2566364   9.24148047 10.49346564]]
Определитель матрицы: 80.83007774435653
След матрицы: 32.652624271976684
Наименьший элемент матрицы: 8.392868012158518
Наибольший элемент матрицы: 11.639502719157376
Норма Фробениуса матрицы: 29.33240989343148
Собственные числа матрицы: [29.20964677  2.16452869  1.27844881]
Обратная матрица:
[[ 0.39015852 -0.14116872 -0.20736722]
 [ 0.03316207  0.32074104 -0.32849846]
 [-0.37337733 -0.15794349  0.56752796]]


#5
Повторите 100 раз следующий эксперимент: сгенерируйте две матрицы
размера 10×10 из стандартного нормального распределения, перемножьте их
(как матрицы) и найдите максимальный элемент. Какое среднее значение по
экспериментам у максимальных элементов? 95-процентная квантиль?

*Кванти́ль в математической статистике — значение, которое заданная случайная величина не превышает с фиксированной вероятностью. Если вероятность задана в процентах, то квантиль называется процентилем или перцентилем*

*Например, фраза «90-й процентиль массы тела у новорожденных мальчиков составляет 4 кг»[1] означает, что 90 % мальчиков рождаются с весом, меньшим либо равным 4 кг, а 10 % мальчиков рождаются с весом, большим либо равным 4 кг.*

In [ ]:
max_vals = []
#Придется использовать циклы
for i in range(100):
    A = np.random.randn(10, 10)
    B = np.random.randn(10, 10)
    C = np.dot(A,B)
    max_val = C.max()
    max_vals.append(max_val)

mean_max = np.mean(max_vals)
quantile_95 = np.percentile(max_vals, 95)

print(f"Среднее значение максимальных элементов: {mean_max}")
print(f"95-процентная квантиль: {quantile_95}")

Среднее значение максимальных элементов: 8.336163468484063
95-процентная квантиль: 11.663774363529127


# Часть 2 **Pandas**

Ответьте на вопросы о данных по авиарейсам в США за январь-апрель
2008 года.
* [Данные](https://www.dropbox.com/s/dvfitn93obn0rql/2008.csv?dl=0)

* [описание](http://stat-computing.org/dataexpo/2009/the-data.html)

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')
import pandas as pd

data = pd.read_csv('/content/drive/MyDrive/Магистратура/4 cем/ПОСИИ/ПР1/2008.csv')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [ ]:
data.head() 

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0  2008      6          18          3   2111.0        2055   2308.0   
1  2008      6           4          3   1426.0        1410   1730.0   
2  2008      8           3          7   1143.0        1145   1501.0   
3  2008      1          23          3   1141.0        1144   1323.0   
4  2008      5           4          7    815.0         820   1243.0   

   CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
0        2300            WN        242  ...    3.0      8.0          0   
1        1728            XE       2380  ...    4.0     12.0          0   
2        1520            WN       1769  ...    4.0      9.0          0   
3        1335            OO       3802  ...    4.0     19.0          0   
4        1300            WN        399  ...    4.0      8.0          0   

   CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
0               NaN         0           NaN          NaN      NaN   
1               NaN         0           NaN          NaN      NaN   
2               NaN         0           NaN          NaN      NaN   
3               NaN         0           NaN          NaN      NaN   
4               NaN         0           NaN          NaN      NaN   

   SecurityDelay  LateAircraftDelay  
0            NaN                NaN  
1            NaN                NaN  
2            NaN                NaN  
3            NaN                NaN  
4            NaN                NaN  

[5 rows x 29 columns]

In [ ]:
list(data.columns.values)

['Year',
 'Month',
 'DayofMonth',
 'DayOfWeek',
 'DepTime',
 'CRSDepTime',
 'ArrTime',
 'CRSArrTime',
 'UniqueCarrier',
 'FlightNum',
 'TailNum',
 'ActualElapsedTime',
 'CRSElapsedTime',
 'AirTime',
 'ArrDelay',
 'DepDelay',
 'Origin',
 'Dest',
 'Distance',
 'TaxiIn',
 'TaxiOut',
 'Cancelled',
 'CancellationCode',
 'Diverted',
 'CarrierDelay',
 'WeatherDelay',
 'NASDelay',
 'SecurityDelay',
 'LateAircraftDelay']

#6

Какая из причин отмены рейса (CancellationCode) была самой частой?
(расшифровки кодов можно найти в описании данных)

* A = carrier 
* B = weather 
* C = NAS
* D = security


In [ ]:
cancellation_counts = data["CancellationCode"].value_counts()
print(cancellation_counts)

A    563
B    549
C    299
Name: CancellationCode, dtype: int64


# 7 
Найдите среднее, минимальное и максимальное расстояние, пройденное самолетом.


In [ ]:
mean_distance = data["Distance"].mean()

min_distance = data["Distance"].min()

max_distance = data["Distance"].max()

print("Среднее расстояние: ", mean_distance)
print("Минимальное расстояние: ", min_distance)
print("Максимальное расстояние: ", max_distance)

Среднее расстояние:  724.5082571428571
Минимальное расстояние:  31
Максимальное расстояние:  4962


#8 
Не выглядит ли подозрительным минимальное пройденное расстояние? В
какие дни и на каких рейсах оно было? Какое расстояние было пройдено этими же рейсами в другие дни?


In [ ]:
# найти записи с минимальным расстоянием
min_distance_flights = data[data["Distance"] == min_distance]

# вывести даты и номера рейсов, в которых было пройдено минимальное расстояние
print("Рейсы с минимальным расстоянием:")
print(min_distance_flights[["Distance", "FlightNum", "Year", "Month", "DayofMonth"]])

# найти записи для тех же рейсов, которые были выполнены в другие дни
same_flights = data[data["FlightNum"].isin(min_distance_flights["FlightNum"])]

# вывести расстояния для тех же рейсов, которые были выполнены в другие дни
print("Расстояния для тех же рейсов, которые были выполнены в другие дни:")
print(same_flights.groupby("FlightNum")["Distance"].mean())

Рейсы с минимальным расстоянием:
       Distance  FlightNum  Year  Month  DayofMonth
1116         31         65  2008     12          30
6958         31         65  2008     12          26
17349        31         64  2008      8          18
27534        31         64  2008      3          11
46082        31         65  2008      8           9
48112        31         64  2008      2          28
Расстояния для тех же рейсов, которые были выполнены в другие дни:
FlightNum
64    748.128205
65    783.512821
Name: Distance, dtype: float64


#9 
Из какого аэропорта было произведено больше всего вылетов? В каком
городе он находится?


In [ ]:
# найти количество вылетов из каждого аэропорта
departures_count = data["Origin"].value_counts()

# найти аэропорт с максимальным количеством вылетов
max_departures_airport = departures_count.idxmax()
max_departures = departures_count.max()
# вывести информацию о максимальном количестве вылетов и городе, в котором находится аэропорт
print(f"Больше всего вылетов ({max_departures}) было произведено из аэропорта {max_departures_airport}.") #В csv нет информации о городе

Больше всего вылетов (4134) было произведено из аэропорта ATL.


# 10 
Найдите для каждого аэропорта среднее время полета (AirTime) по всем
вылетевшим из него рейсам. Какой аэропорт имеет наибольшее значение этого показателя?


In [ ]:
# найти среднее время полета для каждого аэропорта
mean_airtime = data.groupby("Origin")["AirTime"].mean()

# вывести аэропорт с наибольшим средним временем полета
max_airtime_airport = mean_airtime.idxmax()

# вывести информацию о наибольшем среднем времени полета и соответствующем аэропорте
print(f"Наибольшее среднее время полета ({mean_airtime[max_airtime_airport]:.2f} мин) имеет аэропорт {max_airtime_airport}.")


Наибольшее среднее время полета (205.20 мин) имеет аэропорт SJU.


#11 
Найдите аэропорт, у которого наибольшая доля задержанных (DepDelay > 0) рейсов. Исключите при этом из рассмотрения аэропорты, из которых было отправлено меньше 1000 рейсов (используйте функцию filter после groupby).

In [ ]:
# создать фильтр для исключения аэропортов с менее чем 1000 вылетами
airport_filter = data.groupby("Origin").filter(lambda x: len(x) >= 1000)

# найти долю задержанных рейсов по каждому аэропорту
delayed_flights = airport_filter[airport_filter["DepDelay"] > 0].groupby("Origin")["DepDelay"].count() / airport_filter.groupby("Origin")["DepDelay"].count()

# найти аэропорт с максимальной долей задержанных рейсов
max_delayed_airport = delayed_flights.idxmax()

# вывести информацию о максимальной доле задержанных рейсов и городе, в котором находится аэропорт
print(f"Наибольшая доля задержанных рейсов ({delayed_flights[max_delayed_airport]:.2%}) была в аэропорту {max_delayed_airport}.")


Наибольшая доля задержанных рейсов (52.87%) была в аэропорту EWR.
